### PR TITLE
feat: add a test case

### PR DESCRIPTION
**Pull request by srl295**
- Update to sync with https://github.com/keymanapp/keyman/pull/10791
- Update README to describe how to test

### CODE REVIEW

**Review by mcdurdin — COMMENTED** [review]
We'll need to restructure this to be a keyman layout repo. See https://help.keyman.com/developer/17.0/reference/file-layout -- although of course we'll have an xml file not .kmn/.kvks etc

**Comment by srl295** [comment]
> We'll need to restructure this to be a keyman layout repo. See https://help.keyman.com/developer/17.0/reference/file-layout -- although of course we'll have an xml file not .kmn/.kvks etc

how does it deviate from that?

**Comment by srl295** [comment]
@mcdurdin merging so this can be used as a test case, will open separate issue for structure

**Comment by mcdurdin** [comment]
> how does it deviate from that?

It's missing a bunch of files that would be required for it to make it into the keyboards repo, see the link above, but in particular, LICENSE.md, .kpj, .kps, welcome.htm, readme.htm.

However, I don't think this particular keyboard belongs in the keyboards repo, so we may want to move it elsewhere, so that this org stays focused on keyboards published to the repo.

**Pull request merged**
